FROM node:19-alpine as build

WORKDIR /app

# Copiar los archivos de dependencias
COPY client/package*.json ./
COPY client/package-lock.json ./
RUN npm install

# Copiar el código fuente
COPY client/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]